import "antd/dist/antd.css";

import { Layout, PageHeader } from "antd";

import Catalog from "../components/Catalog";
import FooterComponent from "../components/Footer";
import { GetServerSideProps } from "next";
import Head from "next/head";
import HeaderComponent from "../components/Header";
import Image from "next/image";
import { ListOrdemResponse } from "../services/types";
import SiderComponent from "../components/Sider";
import { getOrderList } from "../services/ordem";
import styles from "../../styles/Home.module.css";
import { useEffect } from "react";

const { Content, Footer } = Layout;

interface Props {
  itemsList: ListOrdemResponse;
  searchResults: ListOrdemResponse;
}

export const Home = ({ itemsList, searchResults }: Props) => {
  useEffect(() => {
    console.log(searchResults);
  }, [searchResults]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <HeaderComponent />
        <Layout className={styles.main} hasSider>
          <SiderComponent />
          <Layout>
            <Content>
              <Catalog items={itemsList.itens} />
            </Content>
          </Layout>
        </Layout>
      </Layout>
      <Layout className={styles.footer}>
        <FooterComponent />
      </Layout>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps<Props> = async ({
  query,
}) => {
  // ...
  const data = await getOrderList();
  let searchResults: ListOrdemResponse = null;
  if (query) {
    const { search } = query;
    searchResults = await getOrderList({ pesquisa: search });
  }

  return {
    props: {
      itemsList: data,
      searchResults,
    },
  };
};

export default Home;
